name: Validate Monorepo Access
description: Validates that a monorepo has access to the monorepo features
author: GitHub Expert Services
inputs:
  allowlist_path:
    description: The path to the allowlist file
    required: true
  allowlist_repo:
    description: The repository containing the allowlist in
    required: true
  org:
    description: The slug of the organization
    required: true
  repo:
    description: The slug of the repository
    required: true
  token:
    description: The token to use for authentication
    required: true
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
