

pipeline {
    agent { label 'windows' }

    stages {
        stage('CodeQL - Javascript') {
            steps{
                cleanWs()
                library 'codeql-windows-dev'
                checkout scm
                withCredentials([string(credentialsId: 'github-token', variable: 'TOKEN')]) {
                    ExecuteCodeQL('department-of-veterans-affairs', 'codeql-tools', env.GIT_BRANCH, 'javascript', '', env.TOKEN, true)
                }
                powershell "Rename-Item -Path codeql-scan-results-javascript.csv -NewName codeql-scan-results-javascript-windows.csv"
                archiveArtifacts artifacts: 'codeql-scan-results-javascript-windows.csv', fingerprint: true
            }
        }

        stage('CodeQL with Subdirectories - Javascript') {
            steps{
                cleanWs()
                library 'codeql-windows-dev'
                checkout scm
                dir('verify-scans') {
                    withCredentials([string(credentialsId: 'github-token', variable: 'TOKEN')]) {
                        ExecuteCodeQL('department-of-veterans-affairs', 'codeql-tools', env.GIT_BRANCH, 'javascript', '', env.TOKEN, true)
                    }
                    powershell "Rename-Item -Path codeql-scan-results-javascript.csv -NewName codeql-scan-results-javascript-windows-subdir.csv"
                    archiveArtifacts artifacts: 'codeql-scan-results-javascript-windows-subdir.csv', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
