@Library('codeql-linux-dev')_

void setBuildStatus(String message, String state) {
  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/department-of-veterans-affairs/codeql-tools"],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/codeql-linux"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}

pipeline {
    agent { label 'linux' }

    stages {
        stage('CodeQL - Javascript') {
            steps{
                cleanWs()
                checkout scm
                withCredentials([string(credentialsId: 'github-token', variable: 'TOKEN')]) {
                    ExecuteCodeQL('department-of-veterans-affairs', 'codeql-tools', env.GIT_BRANCH, 'javascript', '', env.TOKEN, true)
                }
                sh "mv codeql-scan-results-javascript.csv codeql-scan-results-javascript-linux.csv"
                archiveArtifacts artifacts: 'codeql-scan-results-javascript-linux.csv', fingerprint: true
            }
        }

        stage('CodeQL with Subdirectories - Javascript') {
            steps{
                cleanWs()
                checkout scm
                dir('verify-scans') {
                    withCredentials([string(credentialsId: 'github-token', variable: 'TOKEN')]) {
                        ExecuteCodeQL('department-of-veterans-affairs', 'codeql-tools', env.GIT_BRANCH, 'javascript', '', env.TOKEN, true)
                    }
                    sh "mv codeql-scan-results-javascript.csv codeql-scan-results-javascript-linux-subdir.csv"
                    archiveArtifacts artifacts: 'codeql-scan-results-javascript-linux-subdir.csv', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            setBuildStatus("Build succeeded", "SUCCESS");
        }
        failure {
            setBuildStatus("Build failed", "FAILURE");
        }
    }
}
