name: Assign Issue

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    name: Assign
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Assign Issue
        uses: pozil/auto-assign-issue@ec7266a6171afb1fcc99708a1bbb6b70d706f5fb
        with:
          assignees: lindluni
          allowSelfAssign: false