name: Enforce GHAS Policy
on:
  pull_request: {}
permissions:
  contents: read
  pull-requests: write
  security-events: read
jobs:
  enforce:
    name: Enforce GHAS Policy
    runs-on: ubuntu-latest
    steps:
      - name: Enforce GHAS Policy
        uses: department-of-veterans-affairs/codeql-tools/enforce-ghas-policy@main
        with:
          message_violation: |
            Your repository is not in compliance with OIS requirements for CodeQL usage.

            Your repository contains **{highAlerts} high severity** vulnerabilities and **{criticalAlerts} critical severity** vulnerabilities.
            
            Per OIS policy, your repository must remediate critical and high vulnerabilities before you may merge additional source code changes. If this Pull Request remediates vulnerabilities, after your Pull Requests CodeQL scan completes, please re-trigger validation by clicking the `Re-run all jobs` button in the top-right corner at this link: <place link here>. Once validation reruns, you will be able to merge your Pull Request.
            
            If this pull request is remediating vulnerabilities and you are not scanning this pull request with CodeQL, your repository GHAS Auditor may bypass this check and merge this pull request after providing justification for performing the merge. Please refer to OIS guidance on providing justification for bypassing this check: <insert link>
            
            For additional information about OIS policy, please refer to the OIS SWA Wiki: https://department-of-veterans-affairs.github.io/ois-swa-wiki/docs/ghas/codeql-usage
